=== gballotta/lolloxml/public/documentoinformatico.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="documento">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="datachiusura" type="xs:date"/>
				<xs:element name="oggettodocumento" type="xs:string" />
				<xs:element name="soggettoproduttore">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nome" type="xs:string"/>
						<xs:element name="cognome" type="xs:string"/>
						<xs:element name="codicefiscale" type="xs:string"/>
					</xs:sequence> </xs:complexType>
				</xs:element>
				<xs:element name="destinatario">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nome" type="xs:string"/>
							<xs:element name="cognome" type="xs:string"/>
							<xs:element name="codicefiscale" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="IDDocumento" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gballotta/lolloxml/public/testdocuinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento IDDocumento="ID001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="documentoinformatico.xsd">
  <datachiusura>2014-11-05</datachiusura>
  <oggettodocumento>Delibera Comunale</oggettodocumento>
  <soggettoproduttore>
    <nome>Giovanni</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLGNN76A15D488B</codicefiscale>
  </soggettoproduttore>
  <destinatario>
    <nome>Lorenzo</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLLNZ79D04D488F</codicefiscale>
  </destinatario>
</documento>

=== gballotta/lolloxml/public/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento IDDocumento="Id15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="documentoinformatico.xsd">
  <datachiusura>15/01/1976</datachiusura>
  <oggettodocumento>Oggetto</oggettodocumento>
  <soggettoproduttore>
    <nome>Giovanni</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLGNN76A15D488B</codicefiscale>
  </soggettoproduttore>
  <destinatario>
    <nome>Giovanni</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLGNN76A15D488B</codicefiscale>
  </destinatario>
  </documento>

=== gballotta/lolloxml/public/documento.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento IDDocumento="Id15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="documentoinformatico.xsd">
  <datachiusura>23/11/2014</datachiusura>
  <oggettodocumento>Diniego</oggettodocumento>
  <soggettoproduttore>
    <nome>Giovanni</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLGNN76A15D488B</codicefiscale>
  </soggettoproduttore>
  <destinatario>
    <nome>Lorenzo</nome>
    <cognome>Ballotta</cognome>
    <codicefiscale>BLLLNZ79D04D488G</codicefiscale>
  </destinatario>
  </documento>
